name: Deploy Go Initializer to Vercel 🚀

on:
  push:
    branches:
      - main        # Trigger on push to main (for production)
      - development # Trigger on push to development (for preview)

# Add concurrency block
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
  # This job runs for pushes to EITHER main or development
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match your project's Node version
          cache: 'npm'
          # Add this line to specify where lock files are located
          cache-dependency-path: '**/package-lock.json'

      - name: Install Server Dependencies
        run: npm ci --prefix server # Use ci for consistency

      - name: Install Client Dependencies
        run: npm ci --prefix client

      - name: Lint Server
        run: echo "Add server lint command if available" # npm run lint --prefix server
        continue-on-error: true # Optional: Don't fail the build for lint errors

      - name: Lint Client
        run: npm run lint --prefix client # Ensure you have a lint script

      - name: Run Server Tests
        run: npm test --prefix server # Ensure you have a test script
        env:
          NODE_ENV: production
          # Add any test-specific environment variables if needed
          # MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }} # Example

      - name: Run Client Tests
        run: npm test --prefix client # Ensure you have a test script

  # This job also runs for pushes to EITHER main or development, after lint-test succeeds
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: lint-test # Only run if the lint-test job succeeds

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Checks out the repository code

      - name: Deploy Project to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Required
          # Conditionally add '--prod' ONLY if the branch is 'main'
          # Otherwise, Vercel automatically creates a preview deployment
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
          # working-directory: ./ # Optional: Specify if your project isn't at the root
